### ISSUE TITLE
workshop-modell: Division by zero error in 1.8.2 (pre_main)

### ISSUE THREAD

**Issue by dunland** [quarree100/q100_abm_TREND#104]
**in pre_main:** (main funktioniert, letzter Commit allerdings vom 25.10.22!)

GAMA subprocess throws division by zero error:

``` bash
Runtime error: Division by zero
Division by zero
	at msi.gama.runtime.exceptions.GamaRuntimeException.error(GamaRuntimeException.java:83)
	at msi.gaml.operators.Maths.opDivide(Maths.java:978)
	at gaml.additions.core.GamlAdditions.lambda$760(GamlAdditions.java:820)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:93)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.statements.SetStatement.privateExecuteIn(SetStatement.java:164)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:468)
	at msi.gama.runtime.IScope.execute(IScope.java:596)
	at msi.gama.runtime.IScope.execute(IScope.java:567)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:72)
	at msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:217)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:62)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:468)
	at msi.gama.runtime.IScope.execute(IScope.java:596)
	at msi.gama.runtime.IScope.execute(IScope.java:567)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:72)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:90)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:62)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:468)
	at msi.gama.runtime.IScope.execute(IScope.java:596)
	at msi.gama.runtime.IScope.execute(IScope.java:567)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:126)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:112)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:468)
	at msi.gama.runtime.IScope.execute(IScope.java:596)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:205)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:241)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:177)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:517)
	at msi.gama.common.interfaces.IScopedStepable.step(IScopedStepable.java:27)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:105)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
reportAndThrowIfNeeded : Division by zero
report error : Division by zero
Runtime error: Division by zero
reportAndThrowIfNeeded : Division by zero
report error : Division by zero
Runtime error: Division by zero
reportAndThrowIfNeeded : Division by zero
report error : Division by zero
Runtime error: Division by zero
reportAndThrowIfNeeded : Division by zero
report error : Division by zero
Runtime error: Division by zero

``` 
usw

- ein Gebäude war ausgewählt (4.05 und 4.04 getestet)
- "4.04:" 
    ``` csv
    id,spec_heat_consumption,spec_power_consumption,energy_source,connection_to_heat_grid,refurbished,save_energy,group
    2.04,134.67302,15.74957,Gas,False,2022,False,0
    ```
- Sanierung = 2022 eingestellt
- Wärmenetzans chluss = 2022

**→ Simulation bricht ab:**
-  date ('2024-12-03 00:00:00') (2.05)
-  date ('2023-12-03 00:00:00') (2.04)

[output-ordner von Test 1 / 4.05](https://github.com/quarree100/q100_abm_TREND/files/12250851/output_20230803_14-27-23.zip)

**Comment by dunland** [comment]
Der Fehler scheint schon mit 8992418 gekommen zu sein.. zumindest zeichnet sich das in meinem Test environment ab.

- [ ] überprüfen, ob es am Q-Scope auch so ist
- [ ] Vermutung prüfen, dass es mit der Voreinstellung der Gebäude zu tun hat: scheinbar funktioniert es, über `devtools.mark_random_buildings_for_simulation`, nicht jedoch "händisch" via:

``` python
# session.buildings.df.loc['2.05', 'refurbished'] = 2022
# session.buildings.df.loc['2.05', 'selected'] = True
# session.buildings.df.loc['2.05', 'group'] = 0
```

Tests mit anderen Gebäuden (z.B. 4.05) erzeugen denselben Fehler..

**Comment by lwinkeler** [comment]
...höchst seltsam. https://github.com/quarree100/q100_abm_TREND/commit/8992418473bf404db161b09130fb1929b4eba778 ist ja am 04.11. geschehen. Also vor den Workshops, bei denen alles funktioniert hat 😵‍💫

**Comment by dunland** [comment]
Ich kann den Fehler in 8992418 gerade nicht mehr reproduzieren :D fuck

**Comment by lwinkeler** [comment]
Was ich zumindest bestätigen kann, ist, dass es bei der spezifischen Auswahl eines Gebäudes liegt.
Das Modell ansich läuft mit der GAMA1.8.2-Version ohne direkte Beeinflussung der Gebäude munter durch.

**Comment by phiola** [comment]
Ich kann den Fehler auch mit der oben genannten Gebäudeauswahl nicht reproduzieren :/

**Comment by lwinkeler** [comment]
Da nicht mehr reproduzierbar: Ich würde das issue schließen, wenn es keine Einwände mehr gibt - bitte einmal um Feedback
